<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <CodeAnalysisRuleSet>.\.stylecop\StyleCopRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="StyleCop.Analyzers" Version="1.0.2"  PrivateAssets="All"/>
    <AdditionalFiles Include=".\.stylecop\stylecop.json" Link="stylecop.json" />
  </ItemGroup>
</Project>
